events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream account_service {
        server 127.0.0.1:3000;
    }

    upstream drawing_service {
        server 127.0.0.1:3001;
    }

    upstream game_service {
        server 127.0.0.1:3002;
    }

    server {
        listen 80;

        root /usr/share/nginx/html;
        index index.html;

        location /api_account/ {
            proxy_pass http://account_service;
        }

        location /api_drawing/ {
            proxy_pass http://drawing_service;
        }

        location /api_game/ {
            proxy_pass http://game_service;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
            expires 1M;
            access_log off;
        }
    }
}
